version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistica
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '9526:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    image: ${DOCKER_USERNAME}/provedor-app:9525
    ports:
      - '9525:9525'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/logistica?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: